language: python
python: 3.7
sudo: false

env:
  global:
    - secure: ""

matrix:
  include:
    - name: Project summary
      python: 3.7
      env: TWINCAT_SUMMARY=1
    - name: Pragma linting
      python: 3.7
      env: TWINCAT_PRAGMALINT=1
    - name: Documentation building
      python: 3.7
      env: TWINCAT_BUILD_DOCS=1

install:
  # Import the helper scripts
  - git clone --depth 1 git://github.com/pcdshub/pcds-ci-helpers.git
  # Start the helper-script initialization + run based on environment variables
  - source pcds-ci-helpers/travis/init.sh
